### ISSUE TITLE
Not accepting credentials at xvnc login.

### ISSUE THREAD

**Issue by PlaceyAUS** [enavarrom/HVFedoraEnhancedSessionMode#1]
Everything installed fine, no issues.  No errors.  Fedora 40 KDE Spin.
Selected desired resolution got to login xvnc.
Wrong username or password I believe it said.  Triple Checked.  Will not except any credentials.

**Comment by PlaceyAUS** [comment]
Sorry proper response was.  User does not exist or could not be authenticated.

**Comment by enavarroprft** [comment]
Hey, thanks for reporting this issue. Sorry for the delay in the responding, but I've been very busy lately. I only test the script in Fedora with Gnome Desktop, I'm going to test with this version and then I will respond if it's necessary a new script for it.

**Comment by enavarrom** [comment]
@PlaceyAUS I upload a new script for KDE environment. Enjoy it!
